tap "drone/drone"
tap "gitea/tap", "https://gitea.com/gitea/homebrew-gitea"
tap "homebrew/bundle"
tap "homebrew/core"
tap "oven-sh/bun"
brew "gh"
brew "go"
brew "hadolint"
brew "jq"
brew "mdbook"
brew "mkcert"
brew "rclone"
brew "shellcheck"
brew "sqlite"
brew "tea"
brew "drone/drone/drone"
brew "oven-sh/bun/bun"
