#!/bin/bash
set -euo pipefail
cd -- "$(dirname -- "$0")"

for dotfile in .*; do
  [[ $dotfile =~ ^(\.\.?|\.git)$ ]] && continue

  dotfile=$(realpath "$dotfile")
  (
    cd
    ln -svf "$dotfile" .
  )
done
