#!/bin/bash
set -euo pipefail
cd -- "$(dirname -- "$0")"

function install_pkg_packages() {
  local packages
  . packages.bash
  pkg upgrade -y
  pkg install -y "${packages[@]}"
}

function install_termux_task() {
  mkdir -p ~/.shortcuts/tasks
  install -v "$1" ~/.shortcuts/tasks/
}

install_pkg_packages
install_termux_task tasks/logseq-sync
termux-setup-storage
