#!/bin/bash
set -euo pipefail
cd -- "$(dirname -- "$0")"
. ../mod.bash

function install_pkg_packages() {
  local packages
  . packages.bash
  pkg upgrade -y
  pkg install -y "${packages[@]}"
}

install_dotfiles
install_pkg_packages
