#!/bin/sh
set -e
cd ~/logseq
rsync -a ~/storage/shared/logseq/journals/ journals/
rsync -a ~/storage/shared/logseq/pages/ pages/
git add --all
if git commit -m update; then
  rsync -a ./ ~/storage/shared/logseq/
fi
