#!/bin/sh
cd ~/logseq
rsync -a ~/storage/shared/logseq/journals/ journals/
rsync -a ~/storage/shared/logseq/pages/ pages/
git add --all
git commit -m update
rsync -a --update ./ ~/storage/shared/logseq/
