[settings]
paranoid = true
idiomatic_version_file_enable_tools = ["node", "rust"]
install_before = "1d"

[tools]
"cargo:https://github.com/kou029w/jobcan-cli" = "latest"
"core:bun" = "latest"
"core:deno" = "latest"
"core:go" = "latest"
"core:node" = "lts"
"core:rust" = "latest"
"github:astral-sh/uv" = "latest"
"github:block/goose" = "latest"
"github:bluesky-social/goat" = "latest"
"github:cli/cli" = "latest"
"github:hadolint/hadolint" = "latest"
"github:mvdan/sh" = { version = "latest", bin = "shfmt" }
"github:rclone/rclone" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@agentclientprotocol/claude-agent-acp" = "latest"
"npm:@github/copilot" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:heroku" = "latest"
"npm:opencode-ai" = "latest"
"npm:playwright" = "latest"
"npm:pnpm" = "latest"
"npm:serve" = "latest"
"npm:wrangler" = "latest"
