#!/bin/bash
set -euo pipefail
cd -- "$(dirname -- "$0")"
. ../mod.bash

function install_gsettings() {
	local -r gsettings_file=$1
	local -r gsettings_dir=$2
	as_user DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${SUDO_UID:-$UID}/bus" \
		dconf load "${gsettings_dir}" <"$gsettings_file"
}

(($(id -u) == 0)) && install_apt_packages
install_gsettings settings.ini /
install_gsettings terminal-settings.ini "/org/gnome/Ptyxis/Profiles/$(gsettings get org.gnome.Ptyxis default-profile-uuid | tr -d \')/"
install_config
fc-cache
